<?php

return [
    'cache_seconds' => 60,

    'history' => [
        'free_weeks' => 8,
    ],

    'definitions' => [
        [
            'key' => 'workout.structure_builder',
            'group' => 'workout',
            'label' => 'Workout Structure Builder',
            'description' => 'Create and edit structured workout blocks.',
            'athlete_free_enabled' => false,
            'athlete_paid_enabled' => true,
            'coach_paid_enabled' => true,
        ],
        [
            'key' => 'workout.library',
            'group' => 'workout',
            'label' => 'Workout Library',
            'description' => 'Save, reuse, and schedule workout templates.',
            'athlete_free_enabled' => false,
            'athlete_free_limit' => 3,
            'athlete_paid_enabled' => true,
            'coach_paid_enabled' => true,
        ],
        [
            'key' => 'activity.streams',
            'group' => 'activity',
            'label' => 'Activity Streams',
            'description' => 'View timeline stream overlays in session analysis.',
            'athlete_free_enabled' => false,
            'athlete_paid_enabled' => true,
            'coach_paid_enabled' => true,
        ],
        [
            'key' => 'progress.range.extended',
            'group' => 'progress',
            'label' => 'Extended Progress Range',
            'description' => 'Use progress ranges beyond 4 weeks.',
            'athlete_free_enabled' => false,
            'athlete_paid_enabled' => true,
            'coach_paid_enabled' => true,
        ],
        [
            'key' => 'progress.chart.load_trend',
            'group' => 'progress',
            'label' => 'Load Trend Chart',
            'description' => 'Show weekly load trend and recommendation band.',
            'athlete_free_enabled' => false,
            'athlete_paid_enabled' => true,
            'coach_paid_enabled' => true,
        ],
        [
            'key' => 'progress.chart.performance_management',
            'group' => 'progress',
            'label' => 'Performance Management Chart',
            'description' => 'Show CTL, ATL, and TSB chart.',
            'athlete_free_enabled' => false,
            'athlete_paid_enabled' => true,
            'coach_paid_enabled' => true,
        ],
        [
            'key' => 'atp.read',
            'group' => 'atp',
            'label' => 'Annual Training Plan Access',
            'description' => 'View ATP year overview and chart.',
            'athlete_free_enabled' => false,
            'athlete_paid_enabled' => true,
            'coach_paid_enabled' => true,
        ],
        [
            'key' => 'atp.week_edit',
            'group' => 'atp',
            'label' => 'Annual Training Plan Week Editing',
            'description' => 'Edit ATP week type and priority metadata.',
            'athlete_free_enabled' => false,
            'athlete_paid_enabled' => true,
            'coach_paid_enabled' => true,
        ],
        [
            'key' => 'calendar.history.full_depth',
            'group' => 'calendar',
            'label' => 'Full Calendar History',
            'description' => 'Load calendar history beyond free depth limit.',
            'athlete_free_enabled' => false,
            'athlete_paid_enabled' => true,
            'coach_paid_enabled' => true,
        ],
        [
            'key' => 'support.tickets',
            'group' => 'support',
            'label' => 'Support Tickets',
            'description' => 'Create and follow up support tickets.',
            'athlete_free_enabled' => false,
            'athlete_paid_enabled' => true,
            'coach_paid_enabled' => true,
        ],
        [
            'key' => 'ai.future_features',
            'group' => 'ai',
            'label' => 'AI Features (Reserved)',
            'description' => 'Reserved feature gate for upcoming AI capabilities.',
            'athlete_free_enabled' => false,
            'athlete_paid_enabled' => true,
            'coach_paid_enabled' => true,
        ],
    ],
];
